name: shop_app
description: A new Flutter project.

environment:
   sdk: ">=2.7.0 <3.0.0"

dependencies:
   provider: ^5.0.0
   intl: ^0.17.0
   flutter:
      sdk: flutter

   cupertino_icons: ^1.0.2
   http: ^0.13.2
   shared_preferences: ^2.0.5

dev_dependencies:
   flutter_test:
      sdk: flutter

flutter:
   uses-material-design: true
   assets:
      - lib/assets/images/product-placeholder.png
   fonts:
      - family: Anton
        fonts:
           - asset: ./lib/assets/fonts/Anton-Regular.ttf
             weight: 400
      - family: Lato
        fonts:
           - asset: ./lib/assets/fonts/Lato-Regular.ttf
           - asset: ./lib/assets/fonts/Lato-Bold.ttf
             weight: 700
